name = "Abhijit Pachpande"
license = "MIT"
licenselink = "https://github.com/gethugothemes/liva-hugo/blob/master/LICENSE"
description = Abhijit's Blog."
homepage = "http://blog.abhijitpachpande.co.in/"
demosite = "http://blog.abhijitpachpande.co.in/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'gethugothemes', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.58.0"

[author]
  name = "Abhijit Pachpande"
  homepage = "http://blog.abhijitpachpande.co.in/"
